### ISSUE TITLE
複数分散SNSへの対応

### ISSUE THREAD

**Issue by nzws** [nzws/KnzkApp#15]
APIの調査必要あり

**Comment by nzws** [comment]
> Pleroma

とりあえずログインできた
要調査:

- [ ] 画像アップ
- [ ] 文字数

などなど

**Comment by nzws** [comment]
- Pleroma
- Diaspora
- GNU Social

**Comment by yuzulabo** [comment]
とりあえずログインあたりを作っている

**Comment by yuzulabo** [comment]
今思うとなんで一つのアプリに詰め込まなきゃいけないんだ...？

**Comment by nzws** [comment]
一度これ消します
(やめる訳ではなくサービスごとに離す)
