### ISSUE TITLE
なこたの肩書き

### ISSUE THREAD

**Issue by nzws** [nzws/KnzkApp#65]
![image](https://user-images.githubusercontent.com/14953122/40573347-4f03b07a-60fb-11e8-898e-78b6423027fd.png)

ここの肩書き募集してます
今考えてるの:  
- `Gangster of Knzk.me`
- `Moderator of Knzk.me`

案あればコメントにどうぞ

**Comment by GenbuHase** [comment]
I suggest `Yakuza in Knzk.me`

**Comment by ZuZuZuMMO** [comment]
Yakuza no Boss

**Comment by GenbuHase** [comment]
真面目に考えて`Manager of Knzk.me`。
なこたが何してるか分かれば、もっと具体的に出来る気がします。

**Comment by nzws** [comment]
`Boss of Knzk.me`

**Comment by nzws** [comment]
あー真面目なので行くとmodよりManagerの方が良さそう

**Comment by ZuZuZuMMO** [comment]
なこたのトゥートも取り入れながら真面目に考えてHuman Resources Director

**Comment by nzws** [comment]
結構安直すぎない...？

**Comment by ANNotunzdY** [comment]
Shadow ruler of knzk.me

**Comment by nzws** [comment]
これ好き

**Comment by nzws** [comment]
案もこれ以上なさそうなので`Shadow ruler of knzk.me`にしますね
