### ISSUE TITLE
OSのブラウザでログイン

### ISSUE THREAD

**Issue by rinsuki** [nzws/KnzkApp#7]
SFSafariViewController(iOS)とかChromeCustomTabs(Chrome)でログイン画面を表示すると

- ブラウザに保存してあるパスワードが使える
- ブラウザでログイン済みの場合はそのセッションを使ってログイン画面を経由せずそのままOAuth認可画面が表示される

などユーザーにとって大変便利なのでぜひやりましょう

cordovaならこのへんがいいんじゃないでしょうか[未検証]
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller

**Comment by nzws** [comment]
少し前から検討していたのですが、他の事もあって中々対応できませんでした...
自分も思っていたのでやってみます！
