### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by bc1bb** [nzws/KnzkApp#81]
**Is your feature request related to a problem? Please describe.**
I don’t understand japanese and I really want to try knzkapp, but it doesn’t have English support

**Describe the solution you'd like**
Multi-language support, if you translate it in English, the community could help you translating in more language

**Describe alternatives you've considered**
Learn Japanese ? 🤔 

**Additional context**
Hello from [@CM_jusdepatate@mastodon.social](#) :)

[x] I browsed other issues and I didn’t find it

**Comment by nzws** [comment]
Hello!
Thank you for your interest in KnzkApp.

English translation has already been completed. ( [www/locales/en.json](https://github.com/KnzkDev/KnzkApp/blob/master/www/locales/en.json) )
It will be available in the next release.

**Comment by bc1bb** [comment]
Thanks for this response 🙂 
I will take a look at the next release
